// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAemnOp-3NDz96Ev3zbReH8WvTPTtqtF5I',
    appId: '1:357462830523:web:bdd6612618912a36f0689e',
    messagingSenderId: '357462830523',
    projectId: 'parkeasy-bfe67',
    authDomain: 'parkeasy-bfe67.firebaseapp.com',
    storageBucket: 'parkeasy-bfe67.firebasestorage.app',
    measurementId: 'G-SPCXRYRWW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc65GybNm7pFR5PQ88rnIofJhuZNxNFeY',
    appId: '1:357462830523:android:8864d01686399484f0689e',
    messagingSenderId: '357462830523',
    projectId: 'parkeasy-bfe67',
    storageBucket: 'parkeasy-bfe67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKxevT1bYtccklAqsEbUCF2Z5EzxGlpwY',
    appId: '1:357462830523:ios:d156cf289eb51eadf0689e',
    messagingSenderId: '357462830523',
    projectId: 'parkeasy-bfe67',
    storageBucket: 'parkeasy-bfe67.firebasestorage.app',
    iosBundleId: 'com.example.parkeasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKxevT1bYtccklAqsEbUCF2Z5EzxGlpwY',
    appId: '1:357462830523:ios:d156cf289eb51eadf0689e',
    messagingSenderId: '357462830523',
    projectId: 'parkeasy-bfe67',
    storageBucket: 'parkeasy-bfe67.firebasestorage.app',
    iosBundleId: 'com.example.parkeasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAemnOp-3NDz96Ev3zbReH8WvTPTtqtF5I',
    appId: '1:357462830523:web:37cae6adfc61f127f0689e',
    messagingSenderId: '357462830523',
    projectId: 'parkeasy-bfe67',
    authDomain: 'parkeasy-bfe67.firebaseapp.com',
    storageBucket: 'parkeasy-bfe67.firebasestorage.app',
    measurementId: 'G-RXS3XZ6JW8',
  );
}
